import type { LayerDefinition, LayerCategory } from "@/types/layers";

/**
 * Layer registry — defines all available data layers.
 * Actual data fetching and rendering logic is lazy-loaded from each layer's module.
 */
export const LAYER_REGISTRY: LayerDefinition[] = [
  // ── Maritime ──────────────────────────────────────────
  {
    id: "maritime.ais-ships",
    category: "maritime",
    name: "AIS Ship Positions",
    description: "Live vessel positions from AISStream.io (~300 msg/sec global)",
    icon: "Ship",
    defaultEnabled: false,
    renderTarget: "deckgl",
    realtimeSource: "sse",
  },
  {
    id: "maritime.submarine-cables",
    category: "maritime",
    name: "Submarine Cables",
    description: "694 undersea cable routes from TeleGeography",
    icon: "Cable",
    defaultEnabled: false,
    renderTarget: "deckgl",
  },
  {
    id: "maritime.fishing-activity",
    category: "maritime",
    name: "Fishing Activity",
    description: "Global fishing effort heatmap from Global Fishing Watch",
    icon: "Fish",
    defaultEnabled: false,
    renderTarget: "deckgl",
  },
  {
    id: "maritime.dark-vessels",
    category: "maritime",
    name: "Dark Vessels",
    description: "Vessels with AIS gaps or operating without transponders",
    icon: "AlertTriangle",
    defaultEnabled: false,
    renderTarget: "deckgl",
  },

  // ── Aviation ──────────────────────────────────────────
  {
    id: "aviation.commercial-flights",
    category: "aviation",
    name: "Commercial Flights",
    description: "Live aircraft positions from ADSB.fi (~7000+ flights)",
    icon: "Plane",
    defaultEnabled: false,
    renderTarget: "deckgl",
    realtimeSource: "sse",
  },
  {
    id: "aviation.military-flights",
    category: "aviation",
    name: "Military Flights",
    description: "Military aircraft filtered from ADS-B data",
    icon: "Shield",
    defaultEnabled: false,
    renderTarget: "deckgl",
    realtimeSource: "sse",
  },

  // ── Satellites ────────────────────────────────────────
  {
    id: "satellites.active",
    category: "satellites",
    name: "Active Satellites",
    description: "8,000+ active satellites with SGP4 propagation",
    icon: "Satellite",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 60_000,
  },
  {
    id: "satellites.iss",
    category: "satellites",
    name: "ISS Tracking",
    description: "International Space Station live position",
    icon: "Globe",
    defaultEnabled: false,
    renderTarget: "cesium",
    refreshInterval: 5_000,
  },
  {
    id: "satellites.debris",
    category: "satellites",
    name: "Space Debris",
    description: "26,000+ tracked debris objects",
    icon: "Trash2",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 300_000,
  },

  // ── Weather ───────────────────────────────────────────
  {
    id: "weather.current",
    category: "weather",
    name: "Current Weather",
    description: "Temperature, humidity, wind from Open-Meteo",
    icon: "Thermometer",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 600_000,
  },
  {
    id: "weather.radar",
    category: "weather",
    name: "Weather Radar",
    description: "NOAA MRMS radar reflectivity tiles",
    icon: "Radar",
    defaultEnabled: false,
    renderTarget: "cesium",
    refreshInterval: 120_000,
  },
  {
    id: "weather.wind-particles",
    category: "weather",
    name: "Wind Flow",
    description: "Animated wind particle visualization",
    icon: "Wind",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },
  {
    id: "weather.lightning",
    category: "weather",
    name: "Lightning Strikes",
    description: "Real-time lightning from Blitzortung network",
    icon: "Zap",
    defaultEnabled: false,
    renderTarget: "deckgl",
    realtimeSource: "sse",
    refreshInterval: 120_000,
  },

  // ── Seismic ───────────────────────────────────────────
  {
    id: "seismic.earthquakes",
    category: "seismic",
    name: "Earthquakes",
    description: "USGS real-time earthquake feed (1-min updates)",
    icon: "Activity",
    defaultEnabled: false,
    renderTarget: "deckgl",
    realtimeSource: "polling",
    refreshInterval: 60_000,
  },
  {
    id: "seismic.tectonic-plates",
    category: "seismic",
    name: "Tectonic Plates",
    description: "52 tectonic plate boundaries",
    icon: "Map",
    defaultEnabled: false,
    renderTarget: "deckgl",
  },
  {
    id: "seismic.volcanoes",
    category: "seismic",
    name: "Volcanoes",
    description: "1,222 Holocene volcanoes from Smithsonian GVP",
    icon: "Mountain",
    defaultEnabled: false,
    renderTarget: "deckgl",
  },
  {
    id: "seismic.tsunamis",
    category: "seismic",
    name: "Tsunami Alerts",
    description: "NOAA NWS tsunami warnings and advisories",
    icon: "Waves",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 300_000,
  },

  // ── Space Weather ─────────────────────────────────────
  {
    id: "space-weather.aurora",
    category: "space-weather",
    name: "Aurora Forecast",
    description: "NOAA SWPC aurora borealis/australis forecast",
    icon: "Sparkles",
    defaultEnabled: false,
    renderTarget: "cesium",
    refreshInterval: 1_800_000,
  },
  {
    id: "space-weather.solar-wind",
    category: "space-weather",
    name: "Solar Wind",
    description: "DSCOVR real-time solar wind speed and Bz",
    icon: "Sun",
    defaultEnabled: false,
    renderTarget: "both",
    refreshInterval: 60_000,
  },
  {
    id: "space-weather.neo",
    category: "space-weather",
    name: "Near-Earth Objects",
    description: "NASA NEO close approach data",
    icon: "Orbit",
    defaultEnabled: false,
    renderTarget: "cesium",
    refreshInterval: 86_400_000,
  },

  // ── Imagery ───────────────────────────────────────────
  {
    id: "imagery.nasa-gibs",
    category: "imagery",
    name: "NASA GIBS Imagery",
    description: "1000+ satellite imagery products (MODIS, VIIRS)",
    icon: "Image",
    defaultEnabled: false,
    renderTarget: "cesium",
  },
  {
    id: "imagery.sentinel2",
    category: "imagery",
    name: "Sentinel-2",
    description: "Cloud-free global mosaic from Copernicus Sentinel-2 (EOX)",
    icon: "Scan",
    defaultEnabled: false,
    renderTarget: "cesium",
  },
  {
    id: "imagery.nightlights",
    category: "imagery",
    name: "VIIRS Nightlights",
    description: "Night-time visible/NIR light emissions",
    icon: "Lightbulb",
    defaultEnabled: false,
    renderTarget: "cesium",
  },

  // ── Environmental ─────────────────────────────────────
  {
    id: "environmental.wildfires",
    category: "environmental",
    name: "Active Wildfires",
    description: "NASA FIRMS fire hotspots (375m, <1h latency)",
    icon: "Flame",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },
  {
    id: "environmental.deforestation",
    category: "environmental",
    name: "Deforestation Alerts",
    description: "Hansen/Global Forest Watch tree cover loss",
    icon: "TreeDeciduous",
    defaultEnabled: false,
    renderTarget: "cesium",
  },
  {
    id: "environmental.ocean-currents",
    category: "environmental",
    name: "Ocean Currents",
    description: "OSCAR surface current particle animation",
    icon: "Waves",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 86_400_000,
  },
  {
    id: "environmental.coral-reefs",
    category: "environmental",
    name: "Coral Reefs",
    description: "Global coral reef locations and bleaching alerts",
    icon: "Shell",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },
  {
    id: "environmental.sea-ice",
    category: "environmental",
    name: "Sea Ice Extent",
    description: "Arctic/Antarctic sea ice from NASA GIBS",
    icon: "Snowflake",
    defaultEnabled: false,
    renderTarget: "cesium",
  },

  // ── Infrastructure ────────────────────────────────────
  {
    id: "infrastructure.airports",
    category: "infrastructure",
    name: "Airports",
    description: "78,000+ airports from OurAirports",
    icon: "PlaneLanding",
    defaultEnabled: false,
    renderTarget: "deckgl",
    minZoom: 3,
  },
  {
    id: "infrastructure.railways",
    category: "infrastructure",
    name: "Railways",
    description: "Global railway network",
    icon: "Train",
    defaultEnabled: false,
    renderTarget: "deckgl",
    minZoom: 4,
  },
  {
    id: "infrastructure.power-plants",
    category: "infrastructure",
    name: "Power Plants",
    description: "30,000 plants across 164 countries (WRI)",
    icon: "Zap",
    defaultEnabled: false,
    renderTarget: "deckgl",
    minZoom: 3,
  },
  {
    id: "infrastructure.cell-towers",
    category: "infrastructure",
    name: "Cell Towers",
    description: "Global cell tower locations from OpenCelliD",
    icon: "Radio",
    defaultEnabled: false,
    renderTarget: "deckgl",
    minZoom: 8,
  },

  // ── Population & Social ───────────────────────────────
  {
    id: "population.density",
    category: "population",
    name: "Population Density",
    description: "WorldPop 100m resolution population grid",
    icon: "Users",
    defaultEnabled: false,
    renderTarget: "cesium",
  },
  {
    id: "population.gdelt-news",
    category: "population",
    name: "News Events (GDELT)",
    description: "Geocoded global news events (15-min updates)",
    icon: "Newspaper",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 900_000,
  },
  {
    id: "population.conflicts",
    category: "population",
    name: "Armed Conflicts",
    description: "ACLED conflict event data",
    icon: "Swords",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 604_800_000,
  },
  {
    id: "population.wikipedia",
    category: "population",
    name: "Wikipedia POIs",
    description: "Geotagged Wikipedia articles near viewport",
    icon: "BookOpen",
    defaultEnabled: false,
    renderTarget: "deckgl",
    minZoom: 8,
    refreshInterval: 300_000,
  },

  // ── Economic ──────────────────────────────────────────
  {
    id: "economic.trade-flows",
    category: "economic",
    name: "Trade Flows",
    description: "UN Comtrade bilateral trade arcs",
    icon: "ArrowLeftRight",
    defaultEnabled: false,
    renderTarget: "deckgl",
  },
  {
    id: "economic.world-bank",
    category: "economic",
    name: "World Bank Indicators",
    description: "GDP, poverty, education choropleth maps",
    icon: "BarChart3",
    defaultEnabled: false,
    renderTarget: "deckgl",
  },
  {
    id: "economic.bitcoin-nodes",
    category: "economic",
    name: "Bitcoin Nodes",
    description: "23,000+ Bitcoin nodes across 157 countries",
    icon: "Bitcoin",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 600_000,
  },

  // ── Markets (Terminal-sourced layers) ─────────────────
  {
    id: "markets.supply-chain-routes",
    category: "markets",
    name: "Supply Chain Routes",
    description: "AI-researched supply chain arcs, facilities, and chokepoints from the terminal",
    icon: "GitBranch",
    defaultEnabled: false,
    renderTarget: "deckgl",
  },

  // ── OSINT ─────────────────────────────────────────────
  {
    id: "osint.gps-jamming",
    category: "osint",
    name: "GPS Interference",
    description: "GPS jamming/spoofing zones from ADS-B NIC values",
    icon: "ShieldAlert",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 86_400_000,
  },
  {
    id: "osint.sanctions",
    category: "osint",
    name: "Sanctions Map",
    description: "OFAC/EU/UK/UN sanctioned entities overlay",
    icon: "Ban",
    defaultEnabled: false,
    renderTarget: "deckgl",
  },
  {
    id: "osint.border-wait",
    category: "osint",
    name: "Border Wait Times",
    description: "CBP real-time US border crossing delays",
    icon: "Clock",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 300_000,
  },
  {
    id: "osint.radiation",
    category: "osint",
    name: "Radiation Monitoring",
    description: "Safecast/EURDEP radiation sensor data",
    icon: "RadioTower",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },

  // ── Cameras ───────────────────────────────────────────
  {
    id: "cameras.webcams",
    category: "cameras",
    name: "Windy Webcams",
    description: "65,000+ global webcams from Windy",
    icon: "Camera",
    defaultEnabled: false,
    renderTarget: "deckgl",
    minZoom: 5,
    refreshInterval: 600_000,
  },
  {
    id: "cameras.cctv",
    category: "cameras",
    name: "Public CCTV",
    description: "DOT traffic cameras and public streams",
    icon: "Video",
    defaultEnabled: false,
    renderTarget: "deckgl",
    minZoom: 8,
  },

  // ── Historical ────────────────────────────────────────
  {
    id: "historical.timeline",
    category: "historical",
    name: "4D Timeline Replay",
    description: "Historical playback with time scrubber",
    icon: "History",
    defaultEnabled: false,
    renderTarget: "both",
  },

  // ── Markets & Economic ────────────────────────────────
  {
    id: "markets.fred",
    category: "markets",
    name: "FRED Economic Indicators",
    description: "Fed funds rate, yield curve, CPI, unemployment, VIX from St. Louis Fed",
    icon: "BarChart3",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },
  {
    id: "markets.yahoo-finance",
    category: "markets",
    name: "Live Market Quotes",
    description: "SPY, QQQ, BTC, Gold, WTI, VIX — real-time prices from Yahoo Finance",
    icon: "TrendingUp",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 60_000,
  },
  {
    id: "markets.treasury",
    category: "markets",
    name: "US Treasury Data",
    description: "National debt, average interest rates on US government debt",
    icon: "Building",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },
  {
    id: "markets.bls",
    category: "markets",
    name: "BLS Employment Data",
    description: "CPI, unemployment rate, nonfarm payrolls, PPI from Bureau of Labor Statistics",
    icon: "Users",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },
  {
    id: "markets.eia",
    category: "markets",
    name: "EIA Energy Prices",
    description: "WTI, Brent, natural gas prices and crude inventory from EIA",
    icon: "Fuel",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },
  {
    id: "markets.gscpi",
    category: "markets",
    name: "Supply Chain Pressure",
    description: "NY Fed Global Supply Chain Pressure Index — standard deviations from average",
    icon: "GitBranch",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 86_400_000,
  },
  {
    id: "markets.usaspending",
    category: "markets",
    name: "Federal Contracts",
    description: "Recent defense/military procurement contracts from USAspending.gov",
    icon: "FileText",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },

  // ── Health & Humanitarian ─────────────────────────────
  {
    id: "health.who-alerts",
    category: "health",
    name: "WHO Disease Alerts",
    description: "WHO Disease Outbreak News — active disease events in last 30 days",
    icon: "AlertTriangle",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },
  {
    id: "health.reliefweb",
    category: "health",
    name: "ReliefWeb Crises",
    description: "UN OCHA humanitarian crises and disaster reports (ReliefWeb)",
    icon: "Heart",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 3_600_000,
  },

  // ── Social & Sentiment ────────────────────────────────
  {
    id: "social.reddit",
    category: "social",
    name: "Reddit Discussions",
    description: "Hot posts from r/worldnews, r/geopolitics, r/economics, r/wallstreetbets",
    icon: "MessageSquare",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 900_000,
  },
  {
    id: "social.bluesky",
    category: "social",
    name: "Bluesky Posts",
    description: "Real-time posts on conflict, markets, and health from Bluesky AT Protocol",
    icon: "MessageCircle",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 300_000,
  },
  {
    id: "social.telegram",
    category: "social",
    name: "Telegram Channels",
    description: "Public OSINT/conflict Telegram channels — conflict intel, Middle East, finance",
    icon: "Send",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 600_000,
  },

  // ── Signals Intelligence ──────────────────────────────
  {
    id: "signals.kiwisdr",
    category: "signals",
    name: "KiwiSDR Network",
    description: "~900 public HF radio receivers worldwide — network usage and conflict zone coverage",
    icon: "Radio",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 600_000,
  },
  {
    id: "signals.patents",
    category: "signals",
    name: "Strategic Patent Filings",
    description: "Recent USPTO patents in AI, quantum, hypersonic, semiconductor, biotech, space",
    icon: "Lightbulb",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 86_400_000,
  },

  // ── News & Media ──────────────────────────────────────
  {
    id: "news.rss-feeds",
    category: "news",
    name: "News Feed Aggregator",
    description: "Live RSS headlines from BBC, Al Jazeera, AP, DW — scrolling ticker",
    icon: "Newspaper",
    defaultEnabled: false,
    renderTarget: "deckgl",
    refreshInterval: 600_000,
  },
];

/** Get all layers for a category */
export function getLayersByCategory(category: LayerCategory): LayerDefinition[] {
  return LAYER_REGISTRY.filter((l) => l.category === category);
}

/** Get a layer definition by ID */
export function getLayerById(id: string): LayerDefinition | undefined {
  return LAYER_REGISTRY.find((l) => l.id === id);
}
